services:
  - type: web
    name: pms-flask
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: true
databases:
  - name: pms-db
    plan: free
